version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    build: .
    container_name: backend-container
    command: /entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./entrypoint.sh:/entrypoint.sh